package com.example.tgmusicai.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Defines the type of audio tone played when an alarm triggers.
 */
enum class AlarmToneType {
    /** Plays a specific user-selected song. */
    SONG,

    /** Plays songs sequentially/shuffled from a user-selected playlist. */
    PLAYLIST,

    /** Plays a random track from the user's most played or liked songs. */
    RANDOM_LIKED
}

/**
 * Room entity representing a scheduled alarm in TGMusicAI.
 *
 * @property id Unique primary key auto-generated by Room.
 * @property timeInMillis Scheduled epoch timestamp or time-of-day representation in milliseconds.
 * @property isEnabled Whether the alarm is currently active and scheduled with system [android.app.AlarmManager].
 * @property repeatDays Comma-separated list of active day numbers (1=Sunday, 2=Monday, ..., 7=Saturday). Empty string indicates a non-repeating alarm.
 * @property toneType The type of music tone to play when triggered ([AlarmToneType]).
 * @property toneUriOrId The song media URI or playlist ID string depending on [toneType].
 * @property snoozeMinutes Duration in minutes for snooze function (defaults to 10 minutes).
 * @property label Optional custom label/description for the alarm (e.g., "Morning Wakeup").
 */
@Entity(tableName = "alarms")
data class Alarm(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val timeInMillis: Long,
    val isEnabled: Boolean = true,
    val repeatDays: String = "",
    val toneType: AlarmToneType = AlarmToneType.RANDOM_LIKED,
    val toneUriOrId: String = "",
    val snoozeMinutes: Int = 10,
    val label: String = "Alarm"
)
