package com.example.tgmusicai.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One chunk of actual listening time for a song, logged periodically during playback (not one row
 * per play) so daily/weekly listening trends can be computed by summing [durationMs] grouped by
 * the day [timestampMs] falls on. A standalone log table rather than a single running total,
 * since [SongStats.totalListenTimeMs] alone can't answer "how much did I listen on Tuesday."
 */
@Entity(tableName = "listening_history")
data class ListeningHistory(
    /** Row ID, auto-generated by Room. Not meaningful outside the row itself. */
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    /** ID of the [Song] this listening chunk belongs to (not a Room foreign key, joined manually in queries). */
    val songId: Long,
    /** Epoch millis when this chunk of listening was logged; used to bucket totals by day/week. */
    val timestampMs: Long = System.currentTimeMillis(),
    /** How long, in milliseconds, playback ran for during this logged chunk. */
    val durationMs: Long
)
