package com.example.tgmusicai.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a playlist created by the user or generated by the app (Smart Playlists).
 */
@Entity(tableName = "playlists")
data class Playlist(
    /**
     * Unique identifier for the playlist.
     */
    @PrimaryKey(autoGenerate = true)
    val playlistId: Long = 0,
    
    /**
     * The display name of the playlist.
     */
    val name: String,

    /**
     * Optional description of the playlist.
     */
    val description: String? = null,

    /**
     * Timestamp (in milliseconds) of when the playlist was created.
     */
    val createdAt: Long = System.currentTimeMillis(),

    /**
     * True if pinned on the Speed Dial Home Tab.
     */
    @ColumnInfo(name = "is_pinned")
    val isPinned: Boolean = false,

    /**
     * True if auto-generated smart playlist (e.g. Top 50 Most Played, Recently Added, Unplayed).
     */
    @ColumnInfo(name = "is_smart")
    val isSmart: Boolean = false,

    /**
     * The source YouTube playlist ID this playlist is synced from (e.g. a user's own playlist ID,
     * or the special "LL" Liked Videos playlist), or null for a regular local/smart playlist.
     */
    @ColumnInfo(name = "youtube_playlist_id")
    val youtubePlaylistId: String? = null,

    /**
     * Epoch millis of the last successful sync from [youtubePlaylistId], or null if never synced
     * (or not a YouTube-synced playlist).
     */
    @ColumnInfo(name = "last_synced_at")
    val lastSyncedAt: Long? = null
)
