package com.example.tgmusicai.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a musical track in the application.
 * Stores metadata about local or cloud streamed music tracks, including lyrics,
 * artwork, youtubeId, download status, and pinning preference.
 */
@Entity(tableName = "songs")
data class Song(
    /**
     * Unique identifier for the song. Auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    
    /**
     * The title of the song.
     */
    val title: String,
    
    /**
     * The artist who performed the song.
     */
    val artist: String,
    
    /**
     * The album the song belongs to.
     */
    val album: String,
    
    /**
     * Duration of the song in milliseconds.
     */
    val durationMs: Long,
    
    /**
     * The local URI, file path, or stream URL where the audio is located.
     */
    val mediaUri: String,

    /**
     * Optional producer metadata extracted from track title or AI metadata cleaning.
     */
    @ColumnInfo(name = "producer")
    val producer: String? = null,

    /**
     * Song lyrics or transcript text (plain text or synced LRC format).
     */
    @ColumnInfo(name = "lyrics")
    val lyrics: String? = null,

    /**
     * Local or remote artwork URI / file path for high-res cover art.
     */
    @ColumnInfo(name = "artworkUri")
    val artworkUri: String? = null,

    /**
     * Optional YouTube video ID for cloud tracks and deduplication.
     */
    @ColumnInfo(name = "youtube_id")
    val youtubeId: String? = null,

    /**
     * True if the audio file is saved locally; false if it's cloud streamable only.
     */
    @ColumnInfo(name = "is_downloaded")
    val isDownloaded: Boolean = true,

    /**
     * True if pinned on the Speed Dial Home Tab.
     */
    @ColumnInfo(name = "is_pinned")
    val isPinned: Boolean = false,

    /**
     * Track loudness relative to the ReplayGain 2.0 reference level (-18 LUFS), in decibels.
     * Negative for tracks louder than the reference, positive for quieter ones -- so applying it
     * brings every track to the same perceived loudness. Read from the file's own
     * `REPLAYGAIN_TRACK_GAIN` tag when present, otherwise measured on-device from decoded audio
     * (see [com.example.tgmusicai.ai.LoudnessAnalyzer]). Null means "not known yet", which plays
     * the track unmodified rather than guessing.
     */
    @ColumnInfo(name = "replay_gain_db")
    val replayGainDb: Float? = null,

    /**
     * Highest absolute sample value in the track, normalized so 1.0 is full scale. Used to clamp
     * the applied gain: boosting a track whose peak is already near 1.0 by its full ReplayGain
     * value would clip. Null when unknown, which makes the limiter fall back to a conservative
     * fixed ceiling.
     */
    @ColumnInfo(name = "replay_peak")
    val replayPeak: Float? = null
)
